### ISSUE TITLE
Add options for justification (e.g. vjust and hjust similar to geom_text())

### ISSUE THREAD

**Issue by rasmus87** [palaeoverse/rphylopic#101]
**Is your feature request related to a problem? Please describe.**
Figure edge position is figure and size dependent, since they all centre on the center of the figure.

**Describe the solution you'd like**
It would be nice with an option like hjust and vjust (as in geom_text()), where vjust = .5 is default figure centre, and vjust = 0 means bottom edge of the figure is exactly on the provided y, and vjust = 1, means the top edge of the figure is exactly on the provided y. 

**Additional context**
An example figure here, where I wish to put all the phylopics bottom edges aligned with the bottom border of the plot:
![ExtinctMammals_](https://github.com/palaeoverse/rphylopic/assets/7794216/b6d6689e-adbb-4ce1-85ac-f992968b63c2)

Thanks for the package, and sorry if the option is available and I just couldn't find it.

**Comment by willgearty** [comment]
Hi @rasmus87, thanks for the suggestion! I'm currently working on an implementation of hjust and vjust in #102. Feel free to take a peak, although it's still not 100% done yet.
