### ISSUE TITLE
Package not working in ggplot call/Image not showing up

### ISSUE THREAD

**Issue by tungxphung** [palaeoverse/rphylopic#108]
Hello, I am trying to use rphylopic but for some reason it is not showing up in the plot (by ggplot2) at all. I am simply copying and pasting the Iris example in the introduction vignette. R takes a few seconds to load the image and work on the ggplot call but then only the points show up and there's simply no image. Saving the file also didn't help.
```
ggplot(iris) +
add_phylopic(x = 6.1, y = 3.2, img = img, alpha = 0.2) +
geom_point(aes(x = Sepal.Length, y = Sepal.Width))
```

However, the image shows up when added to the plot created by base plot()
```
plot(x = 1, y = 1, type = "n")
add_phylopic_base(img = img, x = 1.25, y = 1.25, ysize = 0.25)
```
I am using R/Rstudio 4.3.1. and have only rphylopic and ggplot2 loaded. Any chance you are aware of display issues with ggplot2?

<img width="1440" alt="Screenshot 2024-08-28 at 11 20 09 AM" src="https://github.com/user-attachments/assets/e5c8bcfe-28a8-40ad-be76-ca7daf33874d">

**Comment by LewisAJones** [comment]
Hi @tungxphung, this does seem to be a bug that has creeped in with our latest release. It seems to be an issue with the automatic sizing of the silhouette. If you set `ysize` to a large value, you will see it is actually being plotted.

```
library(ggplot2)
library(rphylopic)
ggplot(iris) +
  add_phylopic(x = 6.1, y = 3.2, name = "Iris", alpha = 0.2, ysize = 500) +
  geom_point(aes(x = Sepal.Length, y = Sepal.Width))
```
![image](https://github.com/user-attachments/assets/6b5dd375-5ad0-4820-83d9-d12413ebae29)

But there seems to also be an issue with the silhouette being plotted upside down, which also needs fixing. For now you can do this by specifying `angle`.

```
library(ggplot2)
library(rphylopic)
ggplot(iris) +
  add_phylopic(x = 6.1, y = 3.2, name = "Iris", alpha = 0.2, 
               ysize = 500, angle = 180) +
  geom_point(aes(x = Sepal.Length, y = Sepal.Width))
```

![image](https://github.com/user-attachments/assets/f4b097d3-87af-46cd-a107-6484ad2aa051)

We are both currently in the middle of moving house but we will look into this next week.

Thanks for bringing it to our attention!

**Comment by willgearty** [comment]
Hi @tungxphung, this is now resolved in the development version of rphylopic on GitHub. If you install the development version, everything should work properly:
```r
install.packages("remotes")
remotes::install_github("palaeoverse/rphylopic")
```
