### ISSUE TITLE
Vectorize add_phylopic and add_phylopic_base

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/rphylopic#42]
Right now `add_phylopic()` and `add_phylopic_base()` can only place a single image in a single location. We should vectorize them so that you can provide multiple locations and/or images in a single call. I was thinking something like how `deeptime::axis_geo()` handles single values and/or lists? Note, this would be different from the new `geom_phylopic()` function for #25.

**Comment by bschilder** [comment]
This would be a really useful feature! Especially because atm the analogous `ggtree` function (`geom_tiplab2(geom="phylopic",...) `) is having quite a few issues:
https://github.com/YuLab-SMU/ggtree/issues
https://github.com/YuLab-SMU/ggtree/issues/567

if you do decide to implement this, it would be even more awesome if circular layouts like ` ggtree::ggtree(layout = "circular",...)` are supported!

Many thanks, 
Brian

**Comment by willgearty** [comment]
Hi @bschilder, the current plan is to make a new `geom_phylopic()` and to make `add_phylopic()` work like `annotate()`. The goal is to get both of these done sometime next week, but no guarantees. I know you have an upcoming deadline for the Bioconductor release (I think you previously mentioned April 5th), and we'll try to prioritize these things, but we likely won't be able to get them on to CRAN by then.

**Comment by bschilder** [comment]
> Hi @bschilder, the current plan is to make a new `geom_phylopic()` and to make `add_phylopic()` work like `annotate()`. The goal is to get both of these done sometime next week, but no guarantees. I know you have an upcoming deadline for the Bioconductor release (I think you previously mentioned April 5th), and we'll try to prioritize these things, but we likely won't be able to get them on to CRAN by then. I can also look into the circular layouts, but that won't necessarily be the priority for this upcoming release.

Thanks so much for keeping me posted on this! No worries about not making it in time for the next Bioc release, I really appreciate you putting the time into making this package even better. Happy to be a tester for any upcoming dev versions.


Thanks again, 
Brian

PS - awesome logo. Love a good hex sticker ;)
