### ISSUE TITLE
Batch viewing for pick_phylopic

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/rphylopic#43]
For some searches, there may be many results for `pick_phylopic()` (e.g., "Cat" or "Animal"). I think the user should be able to specify how many phylopics they want to see at once to speed up the process of picking. The menu would then need to have that many options (plus an option to go to the next batch).

**Comment by willgearty** [comment]
Taxonomically higher order searches will definitely return more than 10 silhouettes (e.g., https://www.phylopic.org/nodes/8ca9a277-8b17-4208-a8b5-c8d55ad516a1/felidae-silhouettes). I don't think a logical argument would be quite as useful as a numeric one.

**Comment by LewisAJones** [comment]
Yes... but as discussed previously the package isn't currently implemented like this... 
We currently search images, not nodes. This would need to change first to be useful in the way you suggest.

This only returns 3 images:
```
get_uuid(name = "Felidae", n = 30)
```

**Comment by willgearty** [comment]
Ah, yes, that's right. Well, just to show that some searches (as they are currently implemented) return more than 10 images:

- "homo" returns 12 images
- "cat" returns 11 images
- "bacteria" returns 30 images

All I'm saying is that the behavior of a logical argument can have dramatically different results depending on the number of images that are returned. For fewer images, they may all be easily visible on a single screen, for many images, like "bacteria", that may not be terribly useful.

**Comment by LewisAJones** [comment]
OK, but we should probably update this long term so the package returns the same silhouettes as what is returned when searching via the Phylopic website?
