### ISSUE TITLE
Use /collections API endpoint

### ISSUE THREAD

**Issue by willgearty** [palaeoverse/rphylopic#81]
Any thoughts about utilizing the `/collections` endpoints on _PhyloPic_ for attribution? You can link to pages like these: https://www.phylopic.org/collections/39f27cb5-5952-01d2-002a-0721a815ac14

There is also a way to turn those into permalinks, although I still need to document that for public usage.

_Originally posted by @keesey in https://github.com/palaeoverse-community/rphylopic/pull/79#issuecomment-1690291905_

**Comment by willgearty** [comment]
@LewisAJones will incorporate this as an option for `get_attribution()`.

@keesey how do we make permalinks for collections through the API?

**Comment by keesey** [comment]
The API Docs show how to create collections. Once you have the collection UUID, you have to use the _website's_ API, which is not currently documented. It's fairly simple, though.

1. Make a `GET` call to `https://www.phylopic.org/api/permalinks/collections/<uuid>`. This will return a hash string.
2. Use that hash string to create a permalink URL: `https://www.phylopic.org/permalinks/<hash>`.
